;;; edit-server-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from edit-server.el

(autoload 'edit-server-start "edit-server" "\
Start the edit server.

If argument VERBOSE is non-nil, logs all server activity to buffer
`*edit-server-log*'.  When called interactivity, a prefix argument
will cause it to be verbose.

(fn &optional VERBOSE)" t)
(register-definition-prefixes "edit-server" '("edit-server-" "global-edit-server-edit-mode" "turn-on-edit-server-edit-mode-if-server"))

;;; End of scraped data

(provide 'edit-server-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; edit-server-autoloads.el ends here
