;;; kotlin-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kotlin-ts-mode.el

(autoload 'kotlin-ts-mode "kotlin-ts-mode" "\
Major mode for editing Kotlin using tree-sitter.

(fn)" t)
(register-definition-prefixes "kotlin-ts-mode" '("kotlin-ts-mode-"))

;;; End of scraped data

(provide 'kotlin-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kotlin-ts-mode-autoloads.el ends here
