;;; svelte-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from svelte-mode.el

(autoload 'svelte-mode "svelte-mode" "\
Major mode based on `html-mode', but works with embedded JS and CSS.

Code inside a <script> element is indented using the rules from
`js-mode'; and code inside a <style> element is indented using
the rules from `css-mode'.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.svelte\\'" . svelte-mode))
(register-definition-prefixes "svelte-mode" '("svelte-"))

;;; End of scraped data

(provide 'svelte-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; svelte-mode-autoloads.el ends here
