;;; base16-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from base16-3024-theme.el

(register-definition-prefixes "base16-3024-theme" '("base16-3024-theme-colors"))


;;; Generated autoloads from base16-apathy-theme.el

(register-definition-prefixes "base16-apathy-theme" '("base16-apathy-theme-colors"))


;;; Generated autoloads from base16-apprentice-theme.el

(register-definition-prefixes "base16-apprentice-theme" '("base16-apprentice-theme-colors"))


;;; Generated autoloads from base16-ashes-theme.el

(register-definition-prefixes "base16-ashes-theme" '("base16-ashes-theme-colors"))


;;; Generated autoloads from base16-atelier-cave-light-theme.el

(register-definition-prefixes "base16-atelier-cave-light-theme" '("base16-atelier-cave-light-theme-colors"))


;;; Generated autoloads from base16-atelier-cave-theme.el

(register-definition-prefixes "base16-atelier-cave-theme" '("base16-atelier-cave-theme-colors"))


;;; Generated autoloads from base16-atelier-dune-light-theme.el

(register-definition-prefixes "base16-atelier-dune-light-theme" '("base16-atelier-dune-light-theme-colors"))


;;; Generated autoloads from base16-atelier-dune-theme.el

(register-definition-prefixes "base16-atelier-dune-theme" '("base16-atelier-dune-theme-colors"))


;;; Generated autoloads from base16-atelier-estuary-light-theme.el

(register-definition-prefixes "base16-atelier-estuary-light-theme" '("base16-atelier-estuary-light-theme-colors"))


;;; Generated autoloads from base16-atelier-estuary-theme.el

(register-definition-prefixes "base16-atelier-estuary-theme" '("base16-atelier-estuary-theme-colors"))


;;; Generated autoloads from base16-atelier-forest-light-theme.el

(register-definition-prefixes "base16-atelier-forest-light-theme" '("base16-atelier-forest-light-theme-colors"))


;;; Generated autoloads from base16-atelier-forest-theme.el

(register-definition-prefixes "base16-atelier-forest-theme" '("base16-atelier-forest-theme-colors"))


;;; Generated autoloads from base16-atelier-heath-light-theme.el

(register-definition-prefixes "base16-atelier-heath-light-theme" '("base16-atelier-heath-light-theme-colors"))


;;; Generated autoloads from base16-atelier-heath-theme.el

(register-definition-prefixes "base16-atelier-heath-theme" '("base16-atelier-heath-theme-colors"))


;;; Generated autoloads from base16-atelier-lakeside-light-theme.el

(register-definition-prefixes "base16-atelier-lakeside-light-theme" '("base16-atelier-lakeside-light-theme-colors"))


;;; Generated autoloads from base16-atelier-lakeside-theme.el

(register-definition-prefixes "base16-atelier-lakeside-theme" '("base16-atelier-lakeside-theme-colors"))


;;; Generated autoloads from base16-atelier-plateau-light-theme.el

(register-definition-prefixes "base16-atelier-plateau-light-theme" '("base16-atelier-plateau-light-theme-colors"))


;;; Generated autoloads from base16-atelier-plateau-theme.el

(register-definition-prefixes "base16-atelier-plateau-theme" '("base16-atelier-plateau-theme-colors"))


;;; Generated autoloads from base16-atelier-savanna-light-theme.el

(register-definition-prefixes "base16-atelier-savanna-light-theme" '("base16-atelier-savanna-light-theme-colors"))


;;; Generated autoloads from base16-atelier-savanna-theme.el

(register-definition-prefixes "base16-atelier-savanna-theme" '("base16-atelier-savanna-theme-colors"))


;;; Generated autoloads from base16-atelier-seaside-light-theme.el

(register-definition-prefixes "base16-atelier-seaside-light-theme" '("base16-atelier-seaside-light-theme-colors"))


;;; Generated autoloads from base16-atelier-seaside-theme.el

(register-definition-prefixes "base16-atelier-seaside-theme" '("base16-atelier-seaside-theme-colors"))


;;; Generated autoloads from base16-atelier-sulphurpool-light-theme.el

(register-definition-prefixes "base16-atelier-sulphurpool-light-theme" '("base16-atelier-sulphurpool-light-theme-colors"))


;;; Generated autoloads from base16-atelier-sulphurpool-theme.el

(register-definition-prefixes "base16-atelier-sulphurpool-theme" '("base16-atelier-sulphurpool-theme-colors"))


;;; Generated autoloads from base16-atlas-theme.el

(register-definition-prefixes "base16-atlas-theme" '("base16-atlas-theme-colors"))


;;; Generated autoloads from base16-ayu-dark-theme.el

(register-definition-prefixes "base16-ayu-dark-theme" '("base16-ayu-dark-theme-colors"))


;;; Generated autoloads from base16-ayu-light-theme.el

(register-definition-prefixes "base16-ayu-light-theme" '("base16-ayu-light-theme-colors"))


;;; Generated autoloads from base16-ayu-mirage-theme.el

(register-definition-prefixes "base16-ayu-mirage-theme" '("base16-ayu-mirage-theme-colors"))


;;; Generated autoloads from base16-aztec-theme.el

(register-definition-prefixes "base16-aztec-theme" '("base16-aztec-theme-colors"))


;;; Generated autoloads from base16-bespin-theme.el

(register-definition-prefixes "base16-bespin-theme" '("base16-bespin-theme-colors"))


;;; Generated autoloads from base16-black-metal-bathory-theme.el

(register-definition-prefixes "base16-black-metal-bathory-theme" '("base16-black-metal-bathory-theme-colors"))


;;; Generated autoloads from base16-black-metal-burzum-theme.el

(register-definition-prefixes "base16-black-metal-burzum-theme" '("base16-black-metal-burzum-theme-colors"))


;;; Generated autoloads from base16-black-metal-dark-funeral-theme.el

(register-definition-prefixes "base16-black-metal-dark-funeral-theme" '("base16-black-metal-dark-funeral-theme-colors"))


;;; Generated autoloads from base16-black-metal-gorgoroth-theme.el

(register-definition-prefixes "base16-black-metal-gorgoroth-theme" '("base16-black-metal-gorgoroth-theme-colors"))


;;; Generated autoloads from base16-black-metal-immortal-theme.el

(register-definition-prefixes "base16-black-metal-immortal-theme" '("base16-black-metal-immortal-theme-colors"))


;;; Generated autoloads from base16-black-metal-khold-theme.el

(register-definition-prefixes "base16-black-metal-khold-theme" '("base16-black-metal-khold-theme-colors"))


;;; Generated autoloads from base16-black-metal-marduk-theme.el

(register-definition-prefixes "base16-black-metal-marduk-theme" '("base16-black-metal-marduk-theme-colors"))


;;; Generated autoloads from base16-black-metal-mayhem-theme.el

(register-definition-prefixes "base16-black-metal-mayhem-theme" '("base16-black-metal-mayhem-theme-colors"))


;;; Generated autoloads from base16-black-metal-nile-theme.el

(register-definition-prefixes "base16-black-metal-nile-theme" '("base16-black-metal-nile-theme-colors"))


;;; Generated autoloads from base16-black-metal-theme.el

(register-definition-prefixes "base16-black-metal-theme" '("base16-black-metal-theme-colors"))


;;; Generated autoloads from base16-black-metal-venom-theme.el

(register-definition-prefixes "base16-black-metal-venom-theme" '("base16-black-metal-venom-theme-colors"))


;;; Generated autoloads from base16-blueforest-theme.el

(register-definition-prefixes "base16-blueforest-theme" '("base16-blueforest-theme-colors"))


;;; Generated autoloads from base16-blueish-theme.el

(register-definition-prefixes "base16-blueish-theme" '("base16-blueish-theme-colors"))


;;; Generated autoloads from base16-brewer-theme.el

(register-definition-prefixes "base16-brewer-theme" '("base16-brewer-theme-colors"))


;;; Generated autoloads from base16-bright-theme.el

(register-definition-prefixes "base16-bright-theme" '("base16-bright-theme-colors"))


;;; Generated autoloads from base16-brogrammer-theme.el

(register-definition-prefixes "base16-brogrammer-theme" '("base16-brogrammer-theme-colors"))


;;; Generated autoloads from base16-brushtrees-dark-theme.el

(register-definition-prefixes "base16-brushtrees-dark-theme" '("base16-brushtrees-dark-theme-colors"))


;;; Generated autoloads from base16-brushtrees-theme.el

(register-definition-prefixes "base16-brushtrees-theme" '("base16-brushtrees-theme-colors"))


;;; Generated autoloads from base16-caroline-theme.el

(register-definition-prefixes "base16-caroline-theme" '("base16-caroline-theme-colors"))


;;; Generated autoloads from base16-catppuccin-frappe-theme.el

(register-definition-prefixes "base16-catppuccin-frappe-theme" '("base16-catppuccin-frappe-theme-colors"))


;;; Generated autoloads from base16-catppuccin-latte-theme.el

(register-definition-prefixes "base16-catppuccin-latte-theme" '("base16-catppuccin-latte-theme-colors"))


;;; Generated autoloads from base16-catppuccin-macchiato-theme.el

(register-definition-prefixes "base16-catppuccin-macchiato-theme" '("base16-catppuccin-macchiato-theme-colors"))


;;; Generated autoloads from base16-catppuccin-mocha-theme.el

(register-definition-prefixes "base16-catppuccin-mocha-theme" '("base16-catppuccin-mocha-theme-colors"))


;;; Generated autoloads from base16-catppuccin-theme.el

(register-definition-prefixes "base16-catppuccin-theme" '("base16-catppuccin-theme-colors"))


;;; Generated autoloads from base16-chalk-theme.el

(register-definition-prefixes "base16-chalk-theme" '("base16-chalk-theme-colors"))


;;; Generated autoloads from base16-circus-theme.el

(register-definition-prefixes "base16-circus-theme" '("base16-circus-theme-colors"))


;;; Generated autoloads from base16-classic-dark-theme.el

(register-definition-prefixes "base16-classic-dark-theme" '("base16-classic-dark-theme-colors"))


;;; Generated autoloads from base16-classic-light-theme.el

(register-definition-prefixes "base16-classic-light-theme" '("base16-classic-light-theme-colors"))


;;; Generated autoloads from base16-codeschool-theme.el

(register-definition-prefixes "base16-codeschool-theme" '("base16-codeschool-theme-colors"))


;;; Generated autoloads from base16-colors-theme.el

(register-definition-prefixes "base16-colors-theme" '("base16-colors-theme-colors"))


;;; Generated autoloads from base16-cupcake-theme.el

(register-definition-prefixes "base16-cupcake-theme" '("base16-cupcake-theme-colors"))


;;; Generated autoloads from base16-cupertino-theme.el

(register-definition-prefixes "base16-cupertino-theme" '("base16-cupertino-theme-colors"))


;;; Generated autoloads from base16-da-one-black-theme.el

(register-definition-prefixes "base16-da-one-black-theme" '("base16-da-one-black-theme-colors"))


;;; Generated autoloads from base16-da-one-gray-theme.el

(register-definition-prefixes "base16-da-one-gray-theme" '("base16-da-one-gray-theme-colors"))


;;; Generated autoloads from base16-da-one-ocean-theme.el

(register-definition-prefixes "base16-da-one-ocean-theme" '("base16-da-one-ocean-theme-colors"))


;;; Generated autoloads from base16-da-one-paper-theme.el

(register-definition-prefixes "base16-da-one-paper-theme" '("base16-da-one-paper-theme-colors"))


;;; Generated autoloads from base16-da-one-sea-theme.el

(register-definition-prefixes "base16-da-one-sea-theme" '("base16-da-one-sea-theme-colors"))


;;; Generated autoloads from base16-da-one-white-theme.el

(register-definition-prefixes "base16-da-one-white-theme" '("base16-da-one-white-theme-colors"))


;;; Generated autoloads from base16-danqing-light-theme.el

(register-definition-prefixes "base16-danqing-light-theme" '("base16-danqing-light-theme-colors"))


;;; Generated autoloads from base16-danqing-theme.el

(register-definition-prefixes "base16-danqing-theme" '("base16-danqing-theme-colors"))


;;; Generated autoloads from base16-darcula-theme.el

(register-definition-prefixes "base16-darcula-theme" '("base16-darcula-theme-colors"))


;;; Generated autoloads from base16-darkmoss-theme.el

(register-definition-prefixes "base16-darkmoss-theme" '("base16-darkmoss-theme-colors"))


;;; Generated autoloads from base16-darktooth-theme.el

(register-definition-prefixes "base16-darktooth-theme" '("base16-darktooth-theme-colors"))


;;; Generated autoloads from base16-darkviolet-theme.el

(register-definition-prefixes "base16-darkviolet-theme" '("base16-darkviolet-theme-colors"))


;;; Generated autoloads from base16-decaf-theme.el

(register-definition-prefixes "base16-decaf-theme" '("base16-decaf-theme-colors"))


;;; Generated autoloads from base16-deep-oceanic-next-theme.el

(register-definition-prefixes "base16-deep-oceanic-next-theme" '("base16-deep-oceanic-next-theme-colors"))


;;; Generated autoloads from base16-default-dark-theme.el

(register-definition-prefixes "base16-default-dark-theme" '("base16-default-dark-theme-colors"))


;;; Generated autoloads from base16-default-light-theme.el

(register-definition-prefixes "base16-default-light-theme" '("base16-default-light-theme-colors"))


;;; Generated autoloads from base16-dirtysea-theme.el

(register-definition-prefixes "base16-dirtysea-theme" '("base16-dirtysea-theme-colors"))


;;; Generated autoloads from base16-dracula-theme.el

(register-definition-prefixes "base16-dracula-theme" '("base16-dracula-theme-colors"))


;;; Generated autoloads from base16-edge-dark-theme.el

(register-definition-prefixes "base16-edge-dark-theme" '("base16-edge-dark-theme-colors"))


;;; Generated autoloads from base16-edge-light-theme.el

(register-definition-prefixes "base16-edge-light-theme" '("base16-edge-light-theme-colors"))


;;; Generated autoloads from base16-eighties-theme.el

(register-definition-prefixes "base16-eighties-theme" '("base16-eighties-theme-colors"))


;;; Generated autoloads from base16-embers-light-theme.el

(register-definition-prefixes "base16-embers-light-theme" '("base16-embers-light-theme-colors"))


;;; Generated autoloads from base16-embers-theme.el

(register-definition-prefixes "base16-embers-theme" '("base16-embers-theme-colors"))


;;; Generated autoloads from base16-emil-theme.el

(register-definition-prefixes "base16-emil-theme" '("base16-emil-theme-colors"))


;;; Generated autoloads from base16-equilibrium-dark-theme.el

(register-definition-prefixes "base16-equilibrium-dark-theme" '("base16-equilibrium-dark-theme-colors"))


;;; Generated autoloads from base16-equilibrium-gray-dark-theme.el

(register-definition-prefixes "base16-equilibrium-gray-dark-theme" '("base16-equilibrium-gray-dark-theme-colors"))


;;; Generated autoloads from base16-equilibrium-gray-light-theme.el

(register-definition-prefixes "base16-equilibrium-gray-light-theme" '("base16-equilibrium-gray-light-theme-colors"))


;;; Generated autoloads from base16-equilibrium-light-theme.el

(register-definition-prefixes "base16-equilibrium-light-theme" '("base16-equilibrium-light-theme-colors"))


;;; Generated autoloads from base16-eris-theme.el

(register-definition-prefixes "base16-eris-theme" '("base16-eris-theme-colors"))


;;; Generated autoloads from base16-espresso-theme.el

(register-definition-prefixes "base16-espresso-theme" '("base16-espresso-theme-colors"))


;;; Generated autoloads from base16-eva-dim-theme.el

(register-definition-prefixes "base16-eva-dim-theme" '("base16-eva-dim-theme-colors"))


;;; Generated autoloads from base16-eva-theme.el

(register-definition-prefixes "base16-eva-theme" '("base16-eva-theme-colors"))


;;; Generated autoloads from base16-evenok-dark-theme.el

(register-definition-prefixes "base16-evenok-dark-theme" '("base16-evenok-dark-theme-colors"))


;;; Generated autoloads from base16-everforest-dark-hard-theme.el

(register-definition-prefixes "base16-everforest-dark-hard-theme" '("base16-everforest-dark-hard-theme-colors"))


;;; Generated autoloads from base16-everforest-theme.el

(register-definition-prefixes "base16-everforest-theme" '("base16-everforest-theme-colors"))


;;; Generated autoloads from base16-flat-theme.el

(register-definition-prefixes "base16-flat-theme" '("base16-flat-theme-colors"))


;;; Generated autoloads from base16-framer-theme.el

(register-definition-prefixes "base16-framer-theme" '("base16-framer-theme-colors"))


;;; Generated autoloads from base16-fruit-soda-theme.el

(register-definition-prefixes "base16-fruit-soda-theme" '("base16-fruit-soda-theme-colors"))


;;; Generated autoloads from base16-gigavolt-theme.el

(register-definition-prefixes "base16-gigavolt-theme" '("base16-gigavolt-theme-colors"))


;;; Generated autoloads from base16-github-theme.el

(register-definition-prefixes "base16-github-theme" '("base16-github-theme-colors"))


;;; Generated autoloads from base16-google-dark-theme.el

(register-definition-prefixes "base16-google-dark-theme" '("base16-google-dark-theme-colors"))


;;; Generated autoloads from base16-google-light-theme.el

(register-definition-prefixes "base16-google-light-theme" '("base16-google-light-theme-colors"))


;;; Generated autoloads from base16-gotham-theme.el

(register-definition-prefixes "base16-gotham-theme" '("base16-gotham-theme-colors"))


;;; Generated autoloads from base16-grayscale-dark-theme.el

(register-definition-prefixes "base16-grayscale-dark-theme" '("base16-grayscale-dark-theme-colors"))


;;; Generated autoloads from base16-grayscale-light-theme.el

(register-definition-prefixes "base16-grayscale-light-theme" '("base16-grayscale-light-theme-colors"))


;;; Generated autoloads from base16-greenscreen-theme.el

(register-definition-prefixes "base16-greenscreen-theme" '("base16-greenscreen-theme-colors"))


;;; Generated autoloads from base16-gruber-theme.el

(register-definition-prefixes "base16-gruber-theme" '("base16-gruber-theme-colors"))


;;; Generated autoloads from base16-gruvbox-dark-hard-theme.el

(register-definition-prefixes "base16-gruvbox-dark-hard-theme" '("base16-gruvbox-dark-hard-theme-colors"))


;;; Generated autoloads from base16-gruvbox-dark-medium-theme.el

(register-definition-prefixes "base16-gruvbox-dark-medium-theme" '("base16-gruvbox-dark-medium-theme-colors"))


;;; Generated autoloads from base16-gruvbox-dark-pale-theme.el

(register-definition-prefixes "base16-gruvbox-dark-pale-theme" '("base16-gruvbox-dark-pale-theme-colors"))


;;; Generated autoloads from base16-gruvbox-dark-soft-theme.el

(register-definition-prefixes "base16-gruvbox-dark-soft-theme" '("base16-gruvbox-dark-soft-theme-colors"))


;;; Generated autoloads from base16-gruvbox-light-hard-theme.el

(register-definition-prefixes "base16-gruvbox-light-hard-theme" '("base16-gruvbox-light-hard-theme-colors"))


;;; Generated autoloads from base16-gruvbox-light-medium-theme.el

(register-definition-prefixes "base16-gruvbox-light-medium-theme" '("base16-gruvbox-light-medium-theme-colors"))


;;; Generated autoloads from base16-gruvbox-light-soft-theme.el

(register-definition-prefixes "base16-gruvbox-light-soft-theme" '("base16-gruvbox-light-soft-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-dark-hard-theme.el

(register-definition-prefixes "base16-gruvbox-material-dark-hard-theme" '("base16-gruvbox-material-dark-hard-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-dark-medium-theme.el

(register-definition-prefixes "base16-gruvbox-material-dark-medium-theme" '("base16-gruvbox-material-dark-medium-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-dark-soft-theme.el

(register-definition-prefixes "base16-gruvbox-material-dark-soft-theme" '("base16-gruvbox-material-dark-soft-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-light-hard-theme.el

(register-definition-prefixes "base16-gruvbox-material-light-hard-theme" '("base16-gruvbox-material-light-hard-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-light-medium-theme.el

(register-definition-prefixes "base16-gruvbox-material-light-medium-theme" '("base16-gruvbox-material-light-medium-theme-colors"))


;;; Generated autoloads from base16-gruvbox-material-light-soft-theme.el

(register-definition-prefixes "base16-gruvbox-material-light-soft-theme" '("base16-gruvbox-material-light-soft-theme-colors"))


;;; Generated autoloads from base16-hardcore-theme.el

(register-definition-prefixes "base16-hardcore-theme" '("base16-hardcore-theme-colors"))


;;; Generated autoloads from base16-harmonic16-dark-theme.el

(register-definition-prefixes "base16-harmonic16-dark-theme" '("base16-harmonic16-dark-theme-colors"))


;;; Generated autoloads from base16-harmonic16-light-theme.el

(register-definition-prefixes "base16-harmonic16-light-theme" '("base16-harmonic16-light-theme-colors"))


;;; Generated autoloads from base16-heetch-light-theme.el

(register-definition-prefixes "base16-heetch-light-theme" '("base16-heetch-light-theme-colors"))


;;; Generated autoloads from base16-heetch-theme.el

(register-definition-prefixes "base16-heetch-theme" '("base16-heetch-theme-colors"))


;;; Generated autoloads from base16-helios-theme.el

(register-definition-prefixes "base16-helios-theme" '("base16-helios-theme-colors"))


;;; Generated autoloads from base16-hopscotch-theme.el

(register-definition-prefixes "base16-hopscotch-theme" '("base16-hopscotch-theme-colors"))


;;; Generated autoloads from base16-horizon-dark-theme.el

(register-definition-prefixes "base16-horizon-dark-theme" '("base16-horizon-dark-theme-colors"))


;;; Generated autoloads from base16-horizon-light-theme.el

(register-definition-prefixes "base16-horizon-light-theme" '("base16-horizon-light-theme-colors"))


;;; Generated autoloads from base16-horizon-terminal-dark-theme.el

(register-definition-prefixes "base16-horizon-terminal-dark-theme" '("base16-horizon-terminal-dark-theme-colors"))


;;; Generated autoloads from base16-horizon-terminal-light-theme.el

(register-definition-prefixes "base16-horizon-terminal-light-theme" '("base16-horizon-terminal-light-theme-colors"))


;;; Generated autoloads from base16-humanoid-dark-theme.el

(register-definition-prefixes "base16-humanoid-dark-theme" '("base16-humanoid-dark-theme-colors"))


;;; Generated autoloads from base16-humanoid-light-theme.el

(register-definition-prefixes "base16-humanoid-light-theme" '("base16-humanoid-light-theme-colors"))


;;; Generated autoloads from base16-ia-dark-theme.el

(register-definition-prefixes "base16-ia-dark-theme" '("base16-ia-dark-theme-colors"))


;;; Generated autoloads from base16-ia-light-theme.el

(register-definition-prefixes "base16-ia-light-theme" '("base16-ia-light-theme-colors"))


;;; Generated autoloads from base16-icy-theme.el

(register-definition-prefixes "base16-icy-theme" '("base16-icy-theme-colors"))


;;; Generated autoloads from base16-irblack-theme.el

(register-definition-prefixes "base16-irblack-theme" '("base16-irblack-theme-colors"))


;;; Generated autoloads from base16-isotope-theme.el

(register-definition-prefixes "base16-isotope-theme" '("base16-isotope-theme-colors"))


;;; Generated autoloads from base16-jabuti-theme.el

(register-definition-prefixes "base16-jabuti-theme" '("base16-jabuti-theme-colors"))


;;; Generated autoloads from base16-kanagawa-theme.el

(register-definition-prefixes "base16-kanagawa-theme" '("base16-kanagawa-theme-colors"))


;;; Generated autoloads from base16-katy-theme.el

(register-definition-prefixes "base16-katy-theme" '("base16-katy-theme-colors"))


;;; Generated autoloads from base16-kimber-theme.el

(register-definition-prefixes "base16-kimber-theme" '("base16-kimber-theme-colors"))


;;; Generated autoloads from base16-lime-theme.el

(register-definition-prefixes "base16-lime-theme" '("base16-lime-theme-colors"))


;;; Generated autoloads from base16-macintosh-theme.el

(register-definition-prefixes "base16-macintosh-theme" '("base16-macintosh-theme-colors"))


;;; Generated autoloads from base16-marrakesh-theme.el

(register-definition-prefixes "base16-marrakesh-theme" '("base16-marrakesh-theme-colors"))


;;; Generated autoloads from base16-materia-theme.el

(register-definition-prefixes "base16-materia-theme" '("base16-materia-theme-colors"))


;;; Generated autoloads from base16-material-darker-theme.el

(register-definition-prefixes "base16-material-darker-theme" '("base16-material-darker-theme-colors"))


;;; Generated autoloads from base16-material-lighter-theme.el

(register-definition-prefixes "base16-material-lighter-theme" '("base16-material-lighter-theme-colors"))


;;; Generated autoloads from base16-material-palenight-theme.el

(register-definition-prefixes "base16-material-palenight-theme" '("base16-material-palenight-theme-colors"))


;;; Generated autoloads from base16-material-theme.el

(register-definition-prefixes "base16-material-theme" '("base16-material-theme-colors"))


;;; Generated autoloads from base16-material-vivid-theme.el

(register-definition-prefixes "base16-material-vivid-theme" '("base16-material-vivid-theme-colors"))


;;; Generated autoloads from base16-measured-dark-theme.el

(register-definition-prefixes "base16-measured-dark-theme" '("base16-measured-dark-theme-colors"))


;;; Generated autoloads from base16-measured-light-theme.el

(register-definition-prefixes "base16-measured-light-theme" '("base16-measured-light-theme-colors"))


;;; Generated autoloads from base16-mellow-purple-theme.el

(register-definition-prefixes "base16-mellow-purple-theme" '("base16-mellow-purple-theme-colors"))


;;; Generated autoloads from base16-mexico-light-theme.el

(register-definition-prefixes "base16-mexico-light-theme" '("base16-mexico-light-theme-colors"))


;;; Generated autoloads from base16-mocha-theme.el

(register-definition-prefixes "base16-mocha-theme" '("base16-mocha-theme-colors"))


;;; Generated autoloads from base16-monokai-theme.el

(register-definition-prefixes "base16-monokai-theme" '("base16-monokai-theme-colors"))


;;; Generated autoloads from base16-moonlight-theme.el

(register-definition-prefixes "base16-moonlight-theme" '("base16-moonlight-theme-colors"))


;;; Generated autoloads from base16-mountain-theme.el

(register-definition-prefixes "base16-mountain-theme" '("base16-mountain-theme-colors"))


;;; Generated autoloads from base16-nebula-theme.el

(register-definition-prefixes "base16-nebula-theme" '("base16-nebula-theme-colors"))


;;; Generated autoloads from base16-nord-light-theme.el

(register-definition-prefixes "base16-nord-light-theme" '("base16-nord-light-theme-colors"))


;;; Generated autoloads from base16-nord-theme.el

(register-definition-prefixes "base16-nord-theme" '("base16-nord-theme-colors"))


;;; Generated autoloads from base16-nova-theme.el

(register-definition-prefixes "base16-nova-theme" '("base16-nova-theme-colors"))


;;; Generated autoloads from base16-ocean-theme.el

(register-definition-prefixes "base16-ocean-theme" '("base16-ocean-theme-colors"))


;;; Generated autoloads from base16-oceanicnext-theme.el

(register-definition-prefixes "base16-oceanicnext-theme" '("base16-oceanicnext-theme-colors"))


;;; Generated autoloads from base16-one-light-theme.el

(register-definition-prefixes "base16-one-light-theme" '("base16-one-light-theme-colors"))


;;; Generated autoloads from base16-onedark-dark-theme.el

(register-definition-prefixes "base16-onedark-dark-theme" '("base16-onedark-dark-theme-colors"))


;;; Generated autoloads from base16-onedark-theme.el

(register-definition-prefixes "base16-onedark-theme" '("base16-onedark-theme-colors"))


;;; Generated autoloads from base16-outrun-dark-theme.el

(register-definition-prefixes "base16-outrun-dark-theme" '("base16-outrun-dark-theme-colors"))


;;; Generated autoloads from base16-oxocarbon-dark-theme.el

(register-definition-prefixes "base16-oxocarbon-dark-theme" '("base16-oxocarbon-dark-theme-colors"))


;;; Generated autoloads from base16-oxocarbon-light-theme.el

(register-definition-prefixes "base16-oxocarbon-light-theme" '("base16-oxocarbon-light-theme-colors"))


;;; Generated autoloads from base16-pandora-theme.el

(register-definition-prefixes "base16-pandora-theme" '("base16-pandora-theme-colors"))


;;; Generated autoloads from base16-papercolor-dark-theme.el

(register-definition-prefixes "base16-papercolor-dark-theme" '("base16-papercolor-dark-theme-colors"))


;;; Generated autoloads from base16-papercolor-light-theme.el

(register-definition-prefixes "base16-papercolor-light-theme" '("base16-papercolor-light-theme-colors"))


;;; Generated autoloads from base16-paraiso-theme.el

(register-definition-prefixes "base16-paraiso-theme" '("base16-paraiso-theme-colors"))


;;; Generated autoloads from base16-pasque-theme.el

(register-definition-prefixes "base16-pasque-theme" '("base16-pasque-theme-colors"))


;;; Generated autoloads from base16-phd-theme.el

(register-definition-prefixes "base16-phd-theme" '("base16-phd-theme-colors"))


;;; Generated autoloads from base16-pico-theme.el

(register-definition-prefixes "base16-pico-theme" '("base16-pico-theme-colors"))


;;; Generated autoloads from base16-pinky-theme.el

(register-definition-prefixes "base16-pinky-theme" '("base16-pinky-theme-colors"))


;;; Generated autoloads from base16-pop-theme.el

(register-definition-prefixes "base16-pop-theme" '("base16-pop-theme-colors"))


;;; Generated autoloads from base16-porple-theme.el

(register-definition-prefixes "base16-porple-theme" '("base16-porple-theme-colors"))


;;; Generated autoloads from base16-precious-dark-eleven-theme.el

(register-definition-prefixes "base16-precious-dark-eleven-theme" '("base16-precious-dark-eleven-theme-colors"))


;;; Generated autoloads from base16-precious-dark-fifteen-theme.el

(register-definition-prefixes "base16-precious-dark-fifteen-theme" '("base16-precious-dark-fifteen-theme-colors"))


;;; Generated autoloads from base16-precious-light-warm-theme.el

(register-definition-prefixes "base16-precious-light-warm-theme" '("base16-precious-light-warm-theme-colors"))


;;; Generated autoloads from base16-precious-light-white-theme.el

(register-definition-prefixes "base16-precious-light-white-theme" '("base16-precious-light-white-theme-colors"))


;;; Generated autoloads from base16-primer-dark-dimmed-theme.el

(register-definition-prefixes "base16-primer-dark-dimmed-theme" '("base16-primer-dark-dimmed-theme-colors"))


;;; Generated autoloads from base16-primer-dark-theme.el

(register-definition-prefixes "base16-primer-dark-theme" '("base16-primer-dark-theme-colors"))


;;; Generated autoloads from base16-primer-light-theme.el

(register-definition-prefixes "base16-primer-light-theme" '("base16-primer-light-theme-colors"))


;;; Generated autoloads from base16-purpledream-theme.el

(register-definition-prefixes "base16-purpledream-theme" '("base16-purpledream-theme-colors"))


;;; Generated autoloads from base16-qualia-theme.el

(register-definition-prefixes "base16-qualia-theme" '("base16-qualia-theme-colors"))


;;; Generated autoloads from base16-railscasts-theme.el

(register-definition-prefixes "base16-railscasts-theme" '("base16-railscasts-theme-colors"))


;;; Generated autoloads from base16-rebecca-theme.el

(register-definition-prefixes "base16-rebecca-theme" '("base16-rebecca-theme-colors"))


;;; Generated autoloads from base16-rose-pine-dawn-theme.el

(register-definition-prefixes "base16-rose-pine-dawn-theme" '("base16-rose-pine-dawn-theme-colors"))


;;; Generated autoloads from base16-rose-pine-moon-theme.el

(register-definition-prefixes "base16-rose-pine-moon-theme" '("base16-rose-pine-moon-theme-colors"))


;;; Generated autoloads from base16-rose-pine-theme.el

(register-definition-prefixes "base16-rose-pine-theme" '("base16-rose-pine-theme-colors"))


;;; Generated autoloads from base16-saga-theme.el

(register-definition-prefixes "base16-saga-theme" '("base16-saga-theme-colors"))


;;; Generated autoloads from base16-sagelight-theme.el

(register-definition-prefixes "base16-sagelight-theme" '("base16-sagelight-theme-colors"))


;;; Generated autoloads from base16-sakura-theme.el

(register-definition-prefixes "base16-sakura-theme" '("base16-sakura-theme-colors"))


;;; Generated autoloads from base16-sandcastle-theme.el

(register-definition-prefixes "base16-sandcastle-theme" '("base16-sandcastle-theme-colors"))


;;; Generated autoloads from base16-selenized-black-theme.el

(register-definition-prefixes "base16-selenized-black-theme" '("base16-selenized-black-theme-colors"))


;;; Generated autoloads from base16-selenized-dark-theme.el

(register-definition-prefixes "base16-selenized-dark-theme" '("base16-selenized-dark-theme-colors"))


;;; Generated autoloads from base16-selenized-light-theme.el

(register-definition-prefixes "base16-selenized-light-theme" '("base16-selenized-light-theme-colors"))


;;; Generated autoloads from base16-selenized-white-theme.el

(register-definition-prefixes "base16-selenized-white-theme" '("base16-selenized-white-theme-colors"))


;;; Generated autoloads from base16-seti-theme.el

(register-definition-prefixes "base16-seti-theme" '("base16-seti-theme-colors"))


;;; Generated autoloads from base16-shades-of-purple-theme.el

(register-definition-prefixes "base16-shades-of-purple-theme" '("base16-shades-of-purple-theme-colors"))


;;; Generated autoloads from base16-shadesmear-dark-theme.el

(register-definition-prefixes "base16-shadesmear-dark-theme" '("base16-shadesmear-dark-theme-colors"))


;;; Generated autoloads from base16-shadesmear-light-theme.el

(register-definition-prefixes "base16-shadesmear-light-theme" '("base16-shadesmear-light-theme-colors"))


;;; Generated autoloads from base16-shapeshifter-theme.el

(register-definition-prefixes "base16-shapeshifter-theme" '("base16-shapeshifter-theme-colors"))


;;; Generated autoloads from base16-silk-dark-theme.el

(register-definition-prefixes "base16-silk-dark-theme" '("base16-silk-dark-theme-colors"))


;;; Generated autoloads from base16-silk-light-theme.el

(register-definition-prefixes "base16-silk-light-theme" '("base16-silk-light-theme-colors"))


;;; Generated autoloads from base16-snazzy-theme.el

(register-definition-prefixes "base16-snazzy-theme" '("base16-snazzy-theme-colors"))


;;; Generated autoloads from base16-solarflare-light-theme.el

(register-definition-prefixes "base16-solarflare-light-theme" '("base16-solarflare-light-theme-colors"))


;;; Generated autoloads from base16-solarflare-theme.el

(register-definition-prefixes "base16-solarflare-theme" '("base16-solarflare-theme-colors"))


;;; Generated autoloads from base16-solarized-dark-theme.el

(register-definition-prefixes "base16-solarized-dark-theme" '("base16-solarized-dark-theme-colors"))


;;; Generated autoloads from base16-solarized-light-theme.el

(register-definition-prefixes "base16-solarized-light-theme" '("base16-solarized-light-theme-colors"))


;;; Generated autoloads from base16-spaceduck-theme.el

(register-definition-prefixes "base16-spaceduck-theme" '("base16-spaceduck-theme-colors"))


;;; Generated autoloads from base16-spacemacs-theme.el

(register-definition-prefixes "base16-spacemacs-theme" '("base16-spacemacs-theme-colors"))


;;; Generated autoloads from base16-sparky-theme.el

(register-definition-prefixes "base16-sparky-theme" '("base16-sparky-theme-colors"))


;;; Generated autoloads from base16-standardized-dark-theme.el

(register-definition-prefixes "base16-standardized-dark-theme" '("base16-standardized-dark-theme-colors"))


;;; Generated autoloads from base16-standardized-light-theme.el

(register-definition-prefixes "base16-standardized-light-theme" '("base16-standardized-light-theme-colors"))


;;; Generated autoloads from base16-stella-theme.el

(register-definition-prefixes "base16-stella-theme" '("base16-stella-theme-colors"))


;;; Generated autoloads from base16-still-alive-theme.el

(register-definition-prefixes "base16-still-alive-theme" '("base16-still-alive-theme-colors"))


;;; Generated autoloads from base16-summercamp-theme.el

(register-definition-prefixes "base16-summercamp-theme" '("base16-summercamp-theme-colors"))


;;; Generated autoloads from base16-summerfruit-dark-theme.el

(register-definition-prefixes "base16-summerfruit-dark-theme" '("base16-summerfruit-dark-theme-colors"))


;;; Generated autoloads from base16-summerfruit-light-theme.el

(register-definition-prefixes "base16-summerfruit-light-theme" '("base16-summerfruit-light-theme-colors"))


;;; Generated autoloads from base16-synth-midnight-dark-theme.el

(register-definition-prefixes "base16-synth-midnight-dark-theme" '("base16-synth-midnight-dark-theme-colors"))


;;; Generated autoloads from base16-synth-midnight-light-theme.el

(register-definition-prefixes "base16-synth-midnight-light-theme" '("base16-synth-midnight-light-theme-colors"))


;;; Generated autoloads from base16-tango-theme.el

(register-definition-prefixes "base16-tango-theme" '("base16-tango-theme-colors"))


;;; Generated autoloads from base16-tarot-theme.el

(register-definition-prefixes "base16-tarot-theme" '("base16-tarot-theme-colors"))


;;; Generated autoloads from base16-tender-theme.el

(register-definition-prefixes "base16-tender-theme" '("base16-tender-theme-colors"))


;;; Generated autoloads from base16-terracotta-dark-theme.el

(register-definition-prefixes "base16-terracotta-dark-theme" '("base16-terracotta-dark-theme-colors"))


;;; Generated autoloads from base16-terracotta-theme.el

(register-definition-prefixes "base16-terracotta-theme" '("base16-terracotta-theme-colors"))


;;; Generated autoloads from base16-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "base16-theme" '("base16-theme-"))


;;; Generated autoloads from base16-tokyo-city-dark-theme.el

(register-definition-prefixes "base16-tokyo-city-dark-theme" '("base16-tokyo-city-dark-theme-colors"))


;;; Generated autoloads from base16-tokyo-city-light-theme.el

(register-definition-prefixes "base16-tokyo-city-light-theme" '("base16-tokyo-city-light-theme-colors"))


;;; Generated autoloads from base16-tokyo-city-terminal-dark-theme.el

(register-definition-prefixes "base16-tokyo-city-terminal-dark-theme" '("base16-tokyo-city-terminal-dark-theme-colors"))


;;; Generated autoloads from base16-tokyo-city-terminal-light-theme.el

(register-definition-prefixes "base16-tokyo-city-terminal-light-theme" '("base16-tokyo-city-terminal-light-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-dark-theme.el

(register-definition-prefixes "base16-tokyo-night-dark-theme" '("base16-tokyo-night-dark-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-light-theme.el

(register-definition-prefixes "base16-tokyo-night-light-theme" '("base16-tokyo-night-light-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-moon-theme.el

(register-definition-prefixes "base16-tokyo-night-moon-theme" '("base16-tokyo-night-moon-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-storm-theme.el

(register-definition-prefixes "base16-tokyo-night-storm-theme" '("base16-tokyo-night-storm-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-terminal-dark-theme.el

(register-definition-prefixes "base16-tokyo-night-terminal-dark-theme" '("base16-tokyo-night-terminal-dark-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-terminal-light-theme.el

(register-definition-prefixes "base16-tokyo-night-terminal-light-theme" '("base16-tokyo-night-terminal-light-theme-colors"))


;;; Generated autoloads from base16-tokyo-night-terminal-storm-theme.el

(register-definition-prefixes "base16-tokyo-night-terminal-storm-theme" '("base16-tokyo-night-terminal-storm-theme-colors"))


;;; Generated autoloads from base16-tokyodark-terminal-theme.el

(register-definition-prefixes "base16-tokyodark-terminal-theme" '("base16-tokyodark-terminal-theme-colors"))


;;; Generated autoloads from base16-tokyodark-theme.el

(register-definition-prefixes "base16-tokyodark-theme" '("base16-tokyodark-theme-colors"))


;;; Generated autoloads from base16-tomorrow-night-eighties-theme.el

(register-definition-prefixes "base16-tomorrow-night-eighties-theme" '("base16-tomorrow-night-eighties-theme-colors"))


;;; Generated autoloads from base16-tomorrow-night-theme.el

(register-definition-prefixes "base16-tomorrow-night-theme" '("base16-tomorrow-night-theme-colors"))


;;; Generated autoloads from base16-tomorrow-theme.el

(register-definition-prefixes "base16-tomorrow-theme" '("base16-tomorrow-theme-colors"))


;;; Generated autoloads from base16-tube-theme.el

(register-definition-prefixes "base16-tube-theme" '("base16-tube-theme-colors"))


;;; Generated autoloads from base16-twilight-theme.el

(register-definition-prefixes "base16-twilight-theme" '("base16-twilight-theme-colors"))


;;; Generated autoloads from base16-unikitty-dark-theme.el

(register-definition-prefixes "base16-unikitty-dark-theme" '("base16-unikitty-dark-theme-colors"))


;;; Generated autoloads from base16-unikitty-light-theme.el

(register-definition-prefixes "base16-unikitty-light-theme" '("base16-unikitty-light-theme-colors"))


;;; Generated autoloads from base16-unikitty-reversible-theme.el

(register-definition-prefixes "base16-unikitty-reversible-theme" '("base16-unikitty-reversible-theme-colors"))


;;; Generated autoloads from base16-uwunicorn-theme.el

(register-definition-prefixes "base16-uwunicorn-theme" '("base16-uwunicorn-theme-colors"))


;;; Generated autoloads from base16-vesper-theme.el

(register-definition-prefixes "base16-vesper-theme" '("base16-vesper-theme-colors"))


;;; Generated autoloads from base16-vice-theme.el

(register-definition-prefixes "base16-vice-theme" '("base16-vice-theme-colors"))


;;; Generated autoloads from base16-vulcan-theme.el

(register-definition-prefixes "base16-vulcan-theme" '("base16-vulcan-theme-colors"))


;;; Generated autoloads from base16-windows-10-light-theme.el

(register-definition-prefixes "base16-windows-10-light-theme" '("base16-windows-10-light-theme-colors"))


;;; Generated autoloads from base16-windows-10-theme.el

(register-definition-prefixes "base16-windows-10-theme" '("base16-windows-10-theme-colors"))


;;; Generated autoloads from base16-windows-95-light-theme.el

(register-definition-prefixes "base16-windows-95-light-theme" '("base16-windows-95-light-theme-colors"))


;;; Generated autoloads from base16-windows-95-theme.el

(register-definition-prefixes "base16-windows-95-theme" '("base16-windows-95-theme-colors"))


;;; Generated autoloads from base16-windows-highcontrast-light-theme.el

(register-definition-prefixes "base16-windows-highcontrast-light-theme" '("base16-windows-highcontrast-light-theme-colors"))


;;; Generated autoloads from base16-windows-highcontrast-theme.el

(register-definition-prefixes "base16-windows-highcontrast-theme" '("base16-windows-highcontrast-theme-colors"))


;;; Generated autoloads from base16-windows-nt-light-theme.el

(register-definition-prefixes "base16-windows-nt-light-theme" '("base16-windows-nt-light-theme-colors"))


;;; Generated autoloads from base16-windows-nt-theme.el

(register-definition-prefixes "base16-windows-nt-theme" '("base16-windows-nt-theme-colors"))


;;; Generated autoloads from base16-woodland-theme.el

(register-definition-prefixes "base16-woodland-theme" '("base16-woodland-theme-colors"))


;;; Generated autoloads from base16-xcode-dusk-theme.el

(register-definition-prefixes "base16-xcode-dusk-theme" '("base16-xcode-dusk-theme-colors"))


;;; Generated autoloads from base16-zenbones-theme.el

(register-definition-prefixes "base16-zenbones-theme" '("base16-zenbones-theme-colors"))


;;; Generated autoloads from base16-zenburn-theme.el

(register-definition-prefixes "base16-zenburn-theme" '("base16-zenburn-theme-colors"))

;;; End of scraped data

(provide 'base16-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; base16-theme-autoloads.el ends here
