;;; thrift-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from thrift.el

(add-to-list 'auto-mode-alist '("\\.thrift$" . thrift-mode))
(autoload 'thrift-mode "thrift" "\
Major mode for editing Thrift files.

(fn)" t)
(register-definition-prefixes "thrift" '("thrift-"))

;;; End of scraped data

(provide 'thrift-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; thrift-autoloads.el ends here
