;;; prettier-js-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from prettier-js.el

(defalias 'prettier-js 'prettier-js-prettify)
(autoload 'prettier-js-prettify "prettier-js" "\
Format the current buffer according to the prettier tool." t)
(autoload 'prettier-js-prettify-region "prettier-js" "\
Format the current region according to the prettier tool." t)
(autoload 'prettier-js-mode "prettier-js" "\
Runs prettier on file save when this mode is turned on

This is a minor mode.  If called interactively, toggle the `Prettier-Js
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `prettier-js-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "prettier-js" '("prettier-js-"))

;;; End of scraped data

(provide 'prettier-js-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; prettier-js-autoloads.el ends here
