;;; company-coq-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-coq.el

(autoload 'company-coq-tutorial "company-coq" "\
Open the company-coq tutorial, creating a new buffer if needed." t)
(autoload 'company-coq-describe-feature "company-coq" "\
Describe company-coq feature FEATURE.

(fn FEATURE)" t)
(autoload 'company-coq-mode "company-coq" "\
Toggle company-coq-mode on or off.

Company-Coq is a collection of Proof-General extensions.  See
https://github.com/cpitclaudel/company-coq/ for a detailed
description, including screenshots and documentation.  First time
users may want to use \\[company-coq-tutorial] to open the
tutorial.

With a prefix argument ARG, enable %s if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil, and toggle it if ARG is `toggle'.

\\{company-coq-map}

(fn &optional ARG)" t)
(autoload 'company-coq-initialize "company-coq" "\
Deprecated: Use `company-coq-mode' instead." t)
(register-definition-prefixes "company-coq" '("company-coq-" "toggle-company-coq-debug"))


;;; Generated autoloads from company-coq-abbrev.el

(register-definition-prefixes "company-coq-abbrev" '("company-coq--refman-"))


;;; Generated autoloads from company-coq-tg.el

(register-definition-prefixes "company-coq-tg" '("company-coq-"))


;;; Generated autoloads from company-coq-utils.el

(autoload 'company-coq-cite "company-coq-utils" "\
Insert BibTeX entries for Coq, PG, and company-coq." t)
(register-definition-prefixes "company-coq-utils" '("company-coq--"))

;;; End of scraped data

(provide 'company-coq-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-coq-autoloads.el ends here
