;;; jsonian-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jsonian.el

(autoload 'jsonian-enclosing-item "jsonian" "\
Move point to the item enclosing the current point.
If ARG is not nil, move to the ARGth enclosing item.

(fn &optional ARG)" t)
(autoload 'jsonian-find "jsonian" "\
Navigate to a item in a JSON document.
If PATH is supplied, navigate to it.

(fn &optional PATH)" t)
(autoload 'jsonian-mode "jsonian" "\
Major mode for editing JSON files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.json\\'" . jsonian-mode))
(autoload 'jsonian-indent-line "jsonian" "\
Indent a single line.
The indent is determined by examining the previous line.  The
number of spaces is determined by `jsonian-indentation' if it is
set, otherwise it is inferred from the document." t)
(autoload 'jsonian-indent-region "jsonian" "\
Indent the region from START to END.

(fn START END)" t)
(autoload 'jsonian-format-region "jsonian" "\
Format the region (START . END).

If MINIMIZE is non-nil, minimize the region instead of expanding it.

(fn START END &optional MINIMIZE)" t)
(autoload 'jsonian-c-mode "jsonian" "\
A major mode for editing JSON documents with comments.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.jsonc\\'" . jsonian-c-mode))
(autoload 'jsonian-enable-flycheck "jsonian" "\
Enable `jsonian-mode' for all checkers where `json-mode' is enabled." t)
(autoload 'jsonian-no-so-long-mode "jsonian" "\
Prevent `so-long-mode' from supplanting `jsonian-mode'." t)
(register-definition-prefixes "jsonian" '("jsonian-"))

;;; End of scraped data

(provide 'jsonian-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jsonian-autoloads.el ends here
