;;; proof-general-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from proof-general.el

(eval-and-compile (defvar pg-init--script-full-path (or (bound-and-true-p byte-compile-current-file) (and load-in-progress load-file-name) (buffer-file-name))) (defvar pg-init--pg-root (file-name-directory pg-init--script-full-path)))
(unless (bound-and-true-p byte-compile-current-file) (require 'proof-site (expand-file-name "generic/proof-site" pg-init--pg-root)))

;;; End of scraped data

(provide 'proof-general-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; proof-general-autoloads.el ends here
