;;; envrc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from envrc.el

(autoload 'envrc-mode "envrc" "\
A local minor mode in which env vars are set by direnv.

This is a minor mode.  If called interactively, toggle the `Envrc mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `envrc-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{envrc-mode-map}

(fn &optional ARG)" t)
(put 'envrc-global-mode 'globalized-minor-mode t)
(defvar envrc-global-mode nil "\
Non-nil if Envrc-Global mode is enabled.
See the `envrc-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `envrc-global-mode'.")
(custom-autoload 'envrc-global-mode "envrc" nil)
(autoload 'envrc-global-mode "envrc" "\
Toggle Envrc mode in all buffers.
With prefix ARG, enable Envrc-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Envrc mode is enabled in all buffers where `(lambda nil (when (cond
((minibufferp) nil) ((file-remote-p default-directory) (and
envrc-remote (seq-contains-p envrc-supported-tramp-methods
(with-parsed-tramp-file-name default-directory vec vec-method)))) (t
(executable-find envrc-direnv-executable))) (envrc-mode 1)))' would do
it.

See `envrc-mode' for more information on Envrc mode.

`envrc-global-modes' is used to control which modes this minor mode is
used in.

(fn &optional ARG)" t)
(defvar envrc-global-modes t "\
Which major modes `envrc-mode' is switched on in.
This variable can be either t (all major modes), nil (no major modes),
or a list of modes and (not modes) to switch use this minor mode or
not.  For instance

  (c-mode (not message-mode mail-mode) text-mode)

means \"use this mode in all modes derived from `c-mode', don't use in
modes derived from `message-mode' or `mail-mode', but do use in other
modes derived from `text-mode'\".  An element with value t means \"use\"
and nil means \"don't use\".  There's an implicit nil at the end of the
list.")
(custom-autoload 'envrc-global-modes "envrc" t)
(autoload 'envrc-file-mode "envrc" "\
Major mode for .envrc files as used by direnv.
\\{envrc-file-mode-map}

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.envrc\\'" . envrc-file-mode))
(register-definition-prefixes "envrc" '("envrc-"))

;;; End of scraped data

(provide 'envrc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; envrc-autoloads.el ends here
