;;; ninja-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ninja-mode.el

(autoload 'ninja-mode "ninja-mode" "\


(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ninja$" . ninja-mode))
(register-definition-prefixes "ninja-mode" '("ninja-"))

;;; End of scraped data

(provide 'ninja-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ninja-mode-autoloads.el ends here
