;;; typst-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from typst-ts-compile.el

(autoload 'typst-ts-compile-and-preview "typst-ts-compile"
"Compile & Preview.
Assuming the compile output file name is in default style." t)
(autoload 'typst-ts-preview "typst-ts-compile"
"Preview the typst document output.
If BUFFER is passed, preview its output, otherwise use current buffer.

(fn &optional BUFFER)" t)
(autoload 'typst-ts-compilation-mode "typst-ts-compile"
"Customized major mode for typst watch compilation.

In addition to any hooks its parent mode `compilation-mode' might have
run, this mode runs the hook `typst-ts-compilation-mode-hook', as the
final or penultimate step during initialization.

\\{typst-ts-compilation-mode-map}" t)
(register-definition-prefixes "typst-ts-compile" '("typst-ts-compil"))


;;; Generated autoloads from typst-ts-core.el

(register-definition-prefixes "typst-ts-core" '("typst-ts-"))


;;; Generated autoloads from typst-ts-edit-indirect.el

(register-definition-prefixes "typst-ts-edit-indirect" '("typst-ts-edit-indirect"))


;;; Generated autoloads from typst-ts-editing.el

(register-definition-prefixes "typst-ts-editing" '("typst-ts-editing-"))


;;; Generated autoloads from typst-ts-embedding-lang-settings.el

(register-definition-prefixes "typst-ts-embedding-lang-settings" '("typst-ts-els-"))


;;; Generated autoloads from typst-ts-faces.el

(register-definition-prefixes "typst-ts-faces" '("typst-ts-markup-header-s"))


;;; Generated autoloads from typst-ts-lsp.el

(autoload 'typst-ts-lsp-download-binary "typst-ts-lsp"
"Download latest tinymist binary to `typst-ts-lsp-download-path'.
Will override old versions." t)
(register-definition-prefixes "typst-ts-lsp" '("typst-ts-lsp-download-path"))


;;; Generated autoloads from typst-ts-misc-commands.el

(register-definition-prefixes "typst-ts-misc-commands" '("typst-ts-mc-"))


;;; Generated autoloads from typst-ts-mode.el

(autoload 'typst-ts-mode "typst-ts-mode"
"Major mode for editing Typst, powered by tree-sitter.

In addition to any hooks its parent mode `text-mode' might have run,
this mode runs the hook `typst-ts-mode-hook', as the final or
penultimate step during initialization.

\\{typst-ts-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.typ\\'" . typst-ts-mode))
(register-definition-prefixes "typst-ts-mode" '("typst-ts-"))


;;; Generated autoloads from typst-ts-symbols.el

(register-definition-prefixes "typst-ts-symbols" '("typst-ts-"))


;;; Generated autoloads from typst-ts-variables.el

(register-definition-prefixes "typst-ts-variables" '("typst-ts-"))


;;; Generated autoloads from typst-ts-watch-mode.el

(autoload 'typst-ts-watch-display-buffer "typst-ts-watch-mode"
"Display typst watch process buffer." t)
(autoload 'typst-ts-watch-start "typst-ts-watch-mode"
"Watch(hot compile) current typst file." t)
(autoload 'typst-ts-watch-stop "typst-ts-watch-mode"
"Stop watch process." t)
(register-definition-prefixes "typst-ts-watch-mode" '("typst-ts-watch-"))

;;; End of scraped data

(provide 'typst-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; typst-ts-mode-autoloads.el ends here
