;;; eldev-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eldev.el

(register-definition-prefixes "eldev" '("eldev-"))


;;; Generated autoloads from eldev-build.el

(register-definition-prefixes "eldev-build" '("eldev-"))


;;; Generated autoloads from eldev-buttercup.el

(register-definition-prefixes "eldev-buttercup" '("eldev-"))


;;; Generated autoloads from eldev-doctest.el

(register-definition-prefixes "eldev-doctest" '("eldev-"))


;;; Generated autoloads from eldev-doctor.el

(register-definition-prefixes "eldev-doctor" '("eldev-"))


;;; Generated autoloads from eldev-ecukes.el

(register-definition-prefixes "eldev-ecukes" '("eldev-"))


;;; Generated autoloads from eldev-ert.el

(register-definition-prefixes "eldev-ert" '("eldev-"))


;;; Generated autoloads from eldev-plugins.el

(register-definition-prefixes "eldev-plugins" '("eldev-"))


;;; Generated autoloads from eldev-util.el

(register-definition-prefixes "eldev-util" '("eldev-"))


;;; Generated autoloads from eldev-vc.el

(register-definition-prefixes "eldev-vc" '("eldev-"))

;;; End of scraped data

(provide 'eldev-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eldev-autoloads.el ends here
