;;; shell-maker-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from markdown-overlays.el

(register-definition-prefixes "markdown-overlays" '("markdown-overlays-"))


;;; Generated autoloads from shell-maker.el

(register-definition-prefixes "shell-maker" '("shell-maker-"))

;;; End of scraped data

(provide 'shell-maker-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; shell-maker-autoloads.el ends here
